name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Check formatting with black
        run: |
          black --check .

      - name: Check import sorting with isort
        run: |
          isort --check-only .

      - name: Run tests with coverage
        run: |
          pytest tests/ --cov=anomaly_detection -v
